# Generated by Django 4.2 on 2024-10-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0002_產品"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="產品",
            name="供應商名稱",
        ),
        migrations.RemoveField(
            model_name="產品",
            name="供應商編號",
        ),
        migrations.RemoveField(
            model_name="產品",
            name="地址",
        ),
        migrations.RemoveField(
            model_name="產品",
            name="統一編號",
        ),
        migrations.RemoveField(
            model_name="產品",
            name="聯絡人",
        ),
        migrations.RemoveField(
            model_name="產品",
            name="電話",
        ),
        migrations.AddField(
            model_name="產品",
            name="供應商序號",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="erp.供應商"
            ),
        ),
        migrations.AlterField(
            model_name="產品",
            name="安全庫存量",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="產品",
            name="庫存量",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="產品",
            name="產品描述",
            field=models.TextField(default=""),
        ),
    ]
