# Generated by Django 4.2 on 2024-10-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0003_remove_產品_供應商名稱_remove_產品_供應商編號_remove_產品_地址_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="產品",
            old_name="供應商序號",
            new_name="供應商",
        ),
        migrations.AlterField(
            model_name="產品",
            name="售價",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="產品",
            name="進貨成本",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="銷售主檔",
            fields=[
                ("序號", models.AutoField(primary_key=True, serialize=False)),
                ("銷售單號", models.CharField(max_length=20)),
                ("銷售日期", models.DateField()),
                ("付款方式", models.CharField(max_length=20)),
                ("運送方式", models.CharField(max_length=20)),
                ("備註", models.TextField(default="")),
                (
                    "客戶",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.客戶",
                    ),
                ),
            ],
        ),
    ]
