# Generated by Django 4.2 on 2024-10-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0004_rename_供應商序號_產品_供應商_alter_產品_售價_alter_產品_進貨成本_銷售主檔"),
    ]

    operations = [
        migrations.CreateModel(
            name="銷售明細",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("數量", models.IntegerField(default=0)),
                ("單價", models.DecimalField(decimal_places=2, max_digits=10)),
                ("折扣", models.DecimalField(decimal_places=2, max_digits=10)),
                ("金額", models.DecimalField(decimal_places=2, max_digits=10)),
                ("備註", models.TextField(default="")),
                (
                    "產品",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.產品",
                    ),
                ),
                (
                    "銷售主檔",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.銷售主檔",
                    ),
                ),
            ],
        ),
    ]
