# Generated by Django 4.2 on 2024-10-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0005_銷售明細"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="銷售明細",
            name="id",
        ),
        migrations.AlterField(
            model_name="銷售明細",
            name="產品",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.產品"
            ),
        ),
        migrations.AlterField(
            model_name="銷售明細",
            name="銷售主檔",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="erp.銷售主檔",
            ),
        ),
    ]
