# Generated by Django 4.2 on 2024-10-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0007_alter_銷售主檔_客戶"),
    ]

    operations = [
        migrations.AlterField(
            model_name="產品",
            name="供應商",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.供應商"
            ),
        ),
    ]
