# Generated by Django 4.2 on 2024-10-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0008_alter_產品_供應商"),
    ]

    operations = [
        migrations.CreateModel(
            name="採購主檔",
            fields=[
                ("序號", models.AutoField(primary_key=True, serialize=False)),
                ("採購單號", models.CharField(max_length=20)),
                ("採購日期", models.DateField()),
                ("預計到貨日期", models.DateField()),
                ("付款方式", models.CharField(max_length=20)),
                ("備註", models.TextField(default="")),
                (
                    "供應商",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.供應商"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="採購明細",
            fields=[
                (
                    "採購主檔",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="erp.採購主檔",
                    ),
                ),
                ("數量", models.IntegerField(default=0)),
                ("單價", models.DecimalField(decimal_places=2, max_digits=10)),
                ("金額", models.DecimalField(decimal_places=2, max_digits=10)),
                ("備註", models.TextField(default="")),
                (
                    "產品",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.產品"
                    ),
                ),
            ],
        ),
    ]
