# Generated by Django 4.2 on 2024-10-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0009_採購主檔_採購明細"),
    ]

    operations = [
        migrations.CreateModel(
            name="庫存",
            fields=[
                ("序號", models.AutoField(primary_key=True, serialize=False)),
                ("庫存數量", models.IntegerField(default=0)),
                ("入庫日期", models.DateField()),
                ("出庫日期", models.DateField()),
                ("備註", models.TextField(default="")),
                (
                    "產品",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.產品"
                    ),
                ),
            ],
        ),
    ]
