# Generated by Django 4.2 on 2024-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0010_庫存"),
    ]

    operations = [
        migrations.AlterField(
            model_name="庫存",
            name="入庫日期",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="庫存",
            name="出庫日期",
            field=models.DateField(null=True),
        ),
    ]
