# Generated by Django 4.2 on 2024-10-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0011_alter_庫存_入庫日期_alter_庫存_出庫日期"),
    ]

    operations = [
        migrations.AlterField(
            model_name="採購主檔",
            name="備註",
            field=models.TextField(null=True),
        ),
    ]
