# Generated by Django 4.2 on 2024-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0013_alter_採購明細_備註_alter_銷售主檔_備註_alter_銷售明細_備註"),
    ]

    operations = [
        migrations.AlterField(
            model_name="產品",
            name="售價",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="產品",
            name="安全庫存量",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="產品",
            name="庫存量",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="產品",
            name="進貨成本",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
