# Generated by Django 4.2 on 2024-11-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0014_alter_產品_售價_alter_產品_安全庫存量_alter_產品_庫存量_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="採購主檔",
            name="狀態",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="銷售主檔",
            name="狀態",
            field=models.TextField(null=True),
        ),
    ]
