# Generated by Django 4.2 on 2024-11-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0015_採購主檔_狀態_銷售主檔_狀態"),
    ]

    operations = [
        migrations.AlterField(
            model_name="採購主檔",
            name="狀態",
            field=models.TextField(default="進行中"),
        ),
        migrations.AlterField(
            model_name="銷售主檔",
            name="狀態",
            field=models.TextField(default="進行中"),
        ),
    ]
