# Generated by Django 4.2 on 2024-11-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0016_alter_採購主檔_狀態_alter_銷售主檔_狀態"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="銷售主檔",
            name="銷售日期",
        ),
        migrations.AddField(
            model_name="銷售主檔",
            name="訂單日期",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="銷售主檔",
            name="預計達交日期",
            field=models.DateField(null=True),
        ),
    ]
