# Generated by Django 4.2 on 2024-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0017_remove_銷售主檔_銷售日期_銷售主檔_訂單日期_銷售主檔_預計達交日期"),
    ]

    operations = [
        migrations.AlterField(
            model_name="銷售主檔",
            name="訂單日期",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="銷售主檔",
            name="預計達交日期",
            field=models.DateField(),
        ),
    ]
