# Generated by Django 4.2 on 2024-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0018_alter_銷售主檔_訂單日期_alter_銷售主檔_預計達交日期"),
    ]

    operations = [
        migrations.AlterField(
            model_name="採購主檔",
            name="狀態",
            field=models.TextField(default="待核准"),
        ),
        migrations.AlterField(
            model_name="銷售主檔",
            name="狀態",
            field=models.TextField(default="待核准"),
        ),
    ]
